# **Practice 14.10.2022. - Markdown**

---

I will also be using HackMD. [Link](https://hackmd.io/?nav=overview)    

## Text decoration

This word is **bold**.  
This word is _italic_.  
These words are **_bold & italic_**.    
We must write this sentence \*italic* and \*\*bold**.

> This is a comment.  
<font color = red>Some red text.</font>   

## Inserting images  

Two ways to insert an image:

![Old FIDIT logo](https://media-exp1.licdn.com/dms/image/C4D0BAQGknJSvyhNAKw/company-logo_200_200/0/1646391178802?e=2147483647&v=beta&t=ew8ZqmVzIdWtnQ2AxPo9_p50iyVnJYuhyyHFOVwREno)  

<img src = "https://media-exp1.licdn.com/dms/image/C4D0BAQGknJSvyhNAKw/company-logo_200_200/0/1646391178802?e=2147483647&v=beta&t=ew8ZqmVzIdWtnQ2AxPo9_p50iyVnJYuhyyHFOVwREno" title = "FIDIT" height = 40%>  

## Writing or embedding code  
  
### C++  
```cpp  
for (int i = 0; i<10; i++)
{
  cout << "Number: " << i;
}
```

# **Practice 14.10.2022. - R**



In [ ]:
# This is a code cell.
# In this cell code can be written and executed.  
c <- 12
c

[1] 12

## Matrixes

In [2]:
first_matrix <- matrix(1:12)  

second_matrix <- matrix(1:7, nrow=3, ncol = 4, byrow = T)
second_matrix

Warning message in matrix(1:7, nrow = 3, ncol = 4, byrow = T):
“data length [7] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    1   
[3,] 2    3    4    5

>_byrow_: matrix content is filled by row (by default, matrix content is filled by column).

In [3]:
r1 <- c(1,2,3)
r2 <- c(4,5,6)
r3 <- c(7,8,9)
matrica2 <- matrix(c(r1, r2, r3), ncol = 4, byrow = T)
matrica2

Warning message in matrix(c(r1, r2, r3), ncol = 4, byrow = T):
“data length [9] is not a sub-multiple or multiple of the number of columns [4]”


[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8   
[3,] 9    1    2    3

In [4]:
pon <- c(6, 15, 19)
uto <- c(0, 6, 7)
sri <- c(-1, 4, 4)
cet <- c(-1, 2, 1)

temperature <- matrix(c(pon, uto, sri, cet), nrow = 4, byrow = T)
# printing the temperature variable:
temperature

[,1] [,2] [,3]
[1,]  6   15   19  
[2,]  0    6    7  
[3,] -1    4    4  
[4,] -1    2    1

> _c_ is a vector!

In [5]:
temperature

[,1] [,2] [,3]
[1,]  6   15   19  
[2,]  0    6    7  
[3,] -1    4    4  
[4,] -1    2    1

> Variables from all cells can be used in any cell.

## Adding row and column names to a matrix

In [6]:
column_names <- c('Morning', 'Afternoon', 'Evening')
row_names <- c('Mon', 'Tue', 'Wed', 'Thu')

rownames(temperature) <- row_names
colnames(temperature) <- column_names
temperature

Morning Afternoon Evening
Mon  6      15        19     
Tue  0       6         7     
Wed -1       4         4     
Thu -1       2         1

## Adding matrix rows and columns

In [7]:
parni <- matrix(seq(2, 18, 2), ncol = 3, byrow = T)
parni
rowSums(parni)
colSums(parni)

matrix(rowSums(parni))
matrix(colSums(parni), 1:3)

[,1] [,2] [,3]
[1,]  2    4    6  
[2,]  8   10   12  
[3,] 14   16   18

[1] 12 30 48

[1] 24 30 36

[,1]
[1,] 12  
[2,] 30  
[3,] 48

[,1] [,2] [,3]
[1,] 24   30   36

## Binding matrixes

In [8]:
Fri <- c(4, 12, 18)
#Binding values from _pet_ matrix to _temperature_ matrix
temperature <- rbind(temperature, Fri)
Sat <- c(2, 4, 6)
temperature <- rbind(temperature, Sat)
Sun <- c(1, 2, 3)
temperature <- rbind(temperature, Sun)
temperature

Morning Afternoon Evening
Mon  6      15        19     
Tue  0       6         7     
Wed -1       4         4     
Thu -1       2         1     
Fri  4      12        18     
Sat  2       4         6     
Sun  1       2         3

In [9]:
Night <- c(0,0,0)
temperature <- cbind(temperature, Night)
Sunrise <- c(2)
temperature <- cbind(temperature, Sunrise)
temperature

Warning message in cbind(temperature, Night):
“number of rows of result is not a multiple of vector length (arg 2)”


Morning Afternoon Evening Night Sunrise
Mon  6      15        19      0     2      
Tue  0       6         7      0     2      
Wed -1       4         4      0     2      
Thu -1       2         1      0     2      
Fri  4      12        18      0     2      
Sat  2       4         6      0     2      
Sun  1       2         3      0     2

In [10]:
Sunrise2 <- c(1,2)
temperature <- cbind(temperature, Sunrise2)
temperature

Warning message in cbind(temperature, Sunrise2):
“number of rows of result is not a multiple of vector length (arg 2)”


Morning Afternoon Evening Night Sunrise Sunrise2
Mon  6      15        19      0     2       1       
Tue  0       6         7      0     2       2       
Wed -1       4         4      0     2       1       
Thu -1       2         1      0     2       2       
Fri  4      12        18      0     2       1       
Sat  2       4         6      0     2       2       
Sun  1       2         3      0     2       1

> Some matrix columns and rows are repeated. This is beacuse a cell has been executed more than once.

In [11]:
# Average temperature value for Afternoon column.
mean(temperature[,'Afternoon'])



[1] 6.428571

## Task 1

In [12]:
#Printing specific row values
temperature[c('Sat', 'Sun'),]
# or
temperature[6:7,] 

#Average temperature during workdays in the morning
mean(temperature[1:5,], 1)
#or
mean(temperature[1:5, c('Morning')])



Morning Afternoon Evening Night Sunrise Sunrise2
Sat 2       4         6       0     2       2       
Sun 1       2         3       0     2       1

Morning Afternoon Evening Night Sunrise Sunrise2
Sat 2       4         6       0     2       2       
Sun 1       2         3       0     2       1

[1] 2

[1] 1.6