<a href="https://colab.research.google.com/github/IvanMatejcic/PMAPI_DAB/blob/main/PMAPI_DAP_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practice 14.10.2022. - Markdown**

---

I will also be using HackMD. [Link](https://hackmd.io/?nav=overview)    

## Text decoration

This word is **bold**.  
This word is _italic_.  
These words are **_bold & italic_**.    
We must write this sentence \*italic* and \*\*bold**.

> This is a comment.  
<font color = red>Some red text.</font>   

## Inserting images  

Two ways to insert an image:

![Old FIDIT logo](https://media-exp1.licdn.com/dms/image/C4D0BAQGknJSvyhNAKw/company-logo_200_200/0/1646391178802?e=2147483647&v=beta&t=ew8ZqmVzIdWtnQ2AxPo9_p50iyVnJYuhyyHFOVwREno)  

<img src = "https://media-exp1.licdn.com/dms/image/C4D0BAQGknJSvyhNAKw/company-logo_200_200/0/1646391178802?e=2147483647&v=beta&t=ew8ZqmVzIdWtnQ2AxPo9_p50iyVnJYuhyyHFOVwREno" title = "FIDIT" height = 40%>  

## Writing or embedding code  
  
### C++  
```cpp  
for (int i = 0; i<10; i++)
{
  cout << "Number: " << i;
}
```

# **Practice 14.10.2022. - R**



In [ ]:
# This is a code cell.
# In this cell code can be written and executed.  
c <- 12
c

[1] 12

## Matrixes

In [ ]:
first_matrix <- matrix(1:12)  

second_matrix <- matrix(1:7, nrow=3, ncol = 4, byrow = T)
second_matrix

Warning message in matrix(1:7, nrow = 3, ncol = 4, byrow = T):
“data length [7] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    1   
[3,] 2    3    4    5

>_byrow_: matrix content is filled by row (by default, matrix content is filled by column).

In [ ]:
r1 <- c(1,2,3)
r2 <- c(4,5,6)
r3 <- c(7,8,9)
matrica2 <- matrix(c(r1, r2, r3), ncol = 4, byrow = T)
matrica2

Warning message in matrix(c(r1, r2, r3), ncol = 4, byrow = T):
“data length [9] is not a sub-multiple or multiple of the number of columns [4]”


[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8   
[3,] 9    1    2    3

In [ ]:
pon <- c(6, 15, 19)
uto <- c(0, 6, 7)
sri <- c(-1, 4, 4)
cet <- c(-1, 2, 1)

temperature <- matrix(c(pon, uto, sri, cet), nrow = 4, byrow = T)
# printing the temperature variable:
temperature

[,1] [,2] [,3]
[1,]  6   15   19  
[2,]  0    6    7  
[3,] -1    4    4  
[4,] -1    2    1

> _c_ is a vector!

In [ ]:
temperature

[,1] [,2] [,3]
[1,]  6   15   19  
[2,]  0    6    7  
[3,] -1    4    4  
[4,] -1    2    1

> Variables from all cells can be used in any cell.

## Adding row and column names to a matrix

In [ ]:
column_names <- c('Morning', 'Afternoon', 'Evening')
row_names <- c('Mon', 'Tue', 'Wed', 'Thu')

rownames(temperature) <- row_names
colnames(temperature) <- column_names
temperature

Morning Afternoon Evening
Mon  6      15        19     
Tue  0       6         7     
Wed -1       4         4     
Thu -1       2         1

## Adding matrix rows and columns

In [ ]:
parni <- matrix(seq(2, 18, 2), ncol = 3, byrow = T)
parni
rowSums(parni)
colSums(parni)

matrix(rowSums(parni))
matrix(colSums(parni), 1:3)

[,1] [,2] [,3]
[1,]  2    4    6  
[2,]  8   10   12  
[3,] 14   16   18

[1] 12 30 48

[1] 24 30 36

[,1]
[1,] 12  
[2,] 30  
[3,] 48

[,1] [,2] [,3]
[1,] 24   30   36

## Binding matrixes

In [ ]:
Fri <- c(4, 12, 18)
#Binding values from _pet_ matrix to _temperature_ matrix
temperature <- rbind(temperature, Fri)
Sat <- c(2, 4, 6)
temperature <- rbind(temperature, Sat)
Sun <- c(1, 2, 3)
temperature <- rbind(temperature, Sun)
temperature

Morning Afternoon Evening
Mon  6      15        19     
Tue  0       6         7     
Wed -1       4         4     
Thu -1       2         1     
Fri  4      12        18     
Sat  2       4         6     
Sun  1       2         3

In [ ]:
Night <- c(0,0,0)
temperature <- cbind(temperature, Night)
Sunrise <- c(2)
temperature <- cbind(temperature, Sunrise)
temperature

Warning message in cbind(temperature, Night):
“number of rows of result is not a multiple of vector length (arg 2)”


Morning Afternoon Evening Night Sunrise
Mon  6      15        19      0     2      
Tue  0       6         7      0     2      
Wed -1       4         4      0     2      
Thu -1       2         1      0     2      
Fri  4      12        18      0     2      
Sat  2       4         6      0     2      
Sun  1       2         3      0     2

In [ ]:
Sunrise2 <- c(1,2)
temperature <- cbind(temperature, Sunrise2)
temperature

Warning message in cbind(temperature, Sunrise2):
“number of rows of result is not a multiple of vector length (arg 2)”


Morning Afternoon Evening Night Sunrise Sunrise2
Mon  6      15        19      0     2       1       
Tue  0       6         7      0     2       2       
Wed -1       4         4      0     2       1       
Thu -1       2         1      0     2       2       
Fri  4      12        18      0     2       1       
Sat  2       4         6      0     2       2       
Sun  1       2         3      0     2       1

> Some matrix columns and rows are repeated. This is beacuse a cell has been executed more than once.

In [ ]:
# Average temperature value for Afternoon column.
mean(temperature[,'Afternoon'])



[1] 6.428571

## Task 1

In [ ]:
#Printing specific row values
temperature[c('Sat', 'Sun'),]
# or
temperature[6:7,] 

#Average temperature during workdays in the morning
mean(temperature[1:5,], 1)
#or
mean(temperature[1:5, c('Morning')])



Morning Afternoon Evening Night Sunrise Sunrise2
Sat 2       4         6       0     2       2       
Sun 1       2         3       0     2       1

Morning Afternoon Evening Night Sunrise Sunrise2
Sat 2       4         6       0     2       2       
Sun 1       2         3       0     2       1

[1] 2

[1] 1.6

# **Practice 28.10.2022 - Logistical Regression**

In [ ]:
# Installing a package with dummy data:
mtcars
#install.packages ('dplyr')
library('dplyr')

In [ ]:
summary(mtcars)

      mpg             cyl             disp             hp       
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
 Median :19.20   Median :6.000   Median :196.3   Median :123.0  
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
      drat             wt             qsec             vs        
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
       am              gear            carb      
 Min.   :0.0000   Min.   :3.000  

In [ ]:
# Generating 20 random numbers from 1 - 50:
sample(c(1:50), 7, replace = T)

[1]  6  8 37 13 28 45 29

In [ ]:
# 80% of rows
n <- round(0.8 * nrow(mtcars))
n


indeksi <- sample(c(1:nrow(mtcars)), n)
#indeksi

#mtcars[indeksi,]
#mtcars[-1]
# Printing mtcars without 1st, 5th & 28th row:
#mtcars[-c(1,5,28)]
set.seed(28)
skup_tren <- mtcars[indeksi, ]
skup_test <- mtcars[-indeksi,]
#
skup_test

[1] 26

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Hornet 4 Drive     21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Merc 280           19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 450SL         17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3   
Cadillac Fleetwood 10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4   
Toyota Corona      21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Fiat X1-9          27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1

In [ ]:
# Binomial regression for all parameters
#logistical_model1 <- glm(vs ~., data = skup_tren, family = "binomial")
#logistical_model1

# Binomial regression for certain parameters
logistical_model2 <- glm(vs ~ wt + disp, data = skup_tren, family = "binomial")
#logistical_model2
#summary(logistical_model2)

# Prediction
prediction <- predict(logistical_model2, skup_test, type = 'response')
#prediction

prediction2 <- ifelse(prediction > 0.5, 1, 0)
#prediction2

#install.packages('caret')

# Confusion matrix:
confusionMatrix <- confusionMatrix(factor(prediction), factor(skup_test$vs))

In [79]:
# TASK

fiat128 <- data.frame(wt = 2.2, disp = 78.7)
fiat128_prediction <-predict(logistical_model2, fiat128, type = 'response')
fiat128_prediction * 100

1 
94.7265